// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://rszkpjvvepafekyxqqeo.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InJzemtwanZ2ZXBhZmVreXhxcWVvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTY2NDI4NDIsImV4cCI6MjA3MjIxODg0Mn0.6wKL1OZ-tN1qvvq1jwUSLOPzoxUYHQ_t43M7xMZ3ZMw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});